### ISSUE TITLE
Can't get Tao Voting to work

### ISSUE THREAD

**Issue by GriffGreen** [CommonsSwarm/commons-upgrade#4]
<img width="711" alt="Screen Shot 2021-12-02 at 2 48 36 PM" src="https://user-images.githubusercontent.com/14945613/144500750-ce011f3e-67e8-40ed-b8b9-1aa88801f53d.png">
<img width="1243" alt="Screen Shot 2021-12-02 at 2 49 01 PM" src="https://user-images.githubusercontent.com/14945613/144500763-d17ad6cc-033d-4a3d-8f8d-eb6972dcd56c.png">

**Comment by PJColombo** [comment]
Hey @GriffGreen, this issue has been solved with the latest evmcrispr version (`v0.3.2`) so it should be working now
